//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.09 at 08:25:37 PM CET 
//

package com.lo.apps.ws.entity.invoice;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * Invoice request elements.
 * 
 * <p>
 * Java class for InvoiceRequest complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requestDateTime" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="invoiceHeaderData" type="{http://localhost:8080/holidayService/}InvoiceHeader"/>
 *         &lt;element name="invoiceRecordData" type="{http://localhost:8080/holidayService/}InvoiceRecord" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceRequest", propOrder = { "requestDateTime", "invoiceHeaderData", "invoiceRecordData" })
public class InvoiceRequest {

	@XmlElement(required = true)
	@XmlSchemaType(name = "date")
	protected Date requestDateTime;
	@XmlElement(required = true)
	protected InvoiceHeader invoiceHeaderData;
	@XmlElement(required = true)
	protected List<InvoiceRecord> invoiceRecordData;

	/**
	 * Gets the value of the requestDateTime property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getRequestDateTime() {
		return requestDateTime;
	}

	/**
	 * Sets the value of the requestDateTime property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setRequestDateTime(Date value) {
		this.requestDateTime = value;
	}

	/**
	 * Gets the value of the invoiceHeaderData property.
	 * 
	 * @return possible object is {@link InvoiceHeader }
	 * 
	 */
	public InvoiceHeader getInvoiceHeaderData() {
		return invoiceHeaderData;
	}

	/**
	 * Sets the value of the invoiceHeaderData property.
	 * 
	 * @param value
	 *            allowed object is {@link InvoiceHeader }
	 * 
	 */
	public void setInvoiceHeaderData(InvoiceHeader value) {
		this.invoiceHeaderData = value;
	}

	/**
	 * Gets the value of the invoiceRecordData property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the invoiceRecordData property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getInvoiceRecordData().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link InvoiceRecord }
	 * 
	 * 
	 */
	public List<InvoiceRecord> getInvoiceRecordData() {
		if (invoiceRecordData == null) {
			invoiceRecordData = new ArrayList<InvoiceRecord>();
		}
		return this.invoiceRecordData;
	}

}
