//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.16 at 08:22:46 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:8080/xwsServer/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.lo.apps.ws.entity.invoice;
