//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 10:49:22 PM CEST 
//


package com.lo.apps.entity;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the localhost._8080.invoiceservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetInvoiceResponse_QNAME = new QName("http://localhost:8080/invoiceService/", "getInvoiceResponse");
    private final static QName _GetInvoiceRequest_QNAME = new QName("http://localhost:8080/invoiceService/", "getInvoiceRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: localhost._8080.invoiceservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InvoiceRequestItems }
     * 
     */
    public InvoiceRequestItems createInvoiceRequestItems() {
        return new InvoiceRequestItems();
    }

    /**
     * Create an instance of {@link InvoiceResponseItems }
     * 
     */
    public InvoiceResponseItems createInvoiceResponseItems() {
        return new InvoiceResponseItems();
    }

    /**
     * Create an instance of {@link InvoiceHeader }
     * 
     */
    public InvoiceHeader createInvoiceHeader() {
        return new InvoiceHeader();
    }

    /**
     * Create an instance of {@link Sums }
     * 
     */
    public Sums createSums() {
        return new Sums();
    }

    /**
     * Create an instance of {@link Transaction }
     * 
     */
    public Transaction createTransaction() {
        return new Transaction();
    }

    /**
     * Create an instance of {@link InvoiceRecord }
     * 
     */
    public InvoiceRecord createInvoiceRecord() {
        return new InvoiceRecord();
    }

    /**
     * Create an instance of {@link Buyer }
     * 
     */
    public Buyer createBuyer() {
        return new Buyer();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccount() {
        return new Account();
    }

    /**
     * Create an instance of {@link Supplier }
     * 
     */
    public Supplier createSupplier() {
        return new Supplier();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvoiceResponseItems }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://localhost:8080/invoiceService/", name = "getInvoiceResponse")
    public JAXBElement<InvoiceResponseItems> createGetInvoiceResponse(InvoiceResponseItems value) {
        return new JAXBElement<InvoiceResponseItems>(_GetInvoiceResponse_QNAME, InvoiceResponseItems.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvoiceRequestItems }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://localhost:8080/invoiceService/", name = "getInvoiceRequest")
    public JAXBElement<InvoiceRequestItems> createGetInvoiceRequest(InvoiceRequestItems value) {
        return new JAXBElement<InvoiceRequestItems>(_GetInvoiceRequest_QNAME, InvoiceRequestItems.class, null, value);
    }

}
